#!/usr/bin/env ruby

# A simple "todo" list for today - by Kevin Hutchinson

require 'yaml'

class Today

  def show_help
    puts <<End_of_help
This is a simple "todo" list for today's tasks.
Here's how to use the "today" command:

> today help              - show this help info
> today                   - list all tasks to finish today
> today get it finished   - add the task "get it finished"
> today done              - remove top item from the list
> today done 2            - remove item 2 from the list
> today first 3           - move item 3 to top of list

End_of_help
  end

  TODAY_HOST = ENV['TODAY_HOST'] # optionally where to sync - a remote hostname
  TODAY_USER = ENV['TODAY_USER'] || ENV['USER'] # the optional user for syncing
  TODAY_PASS = ENV['TODAY_PASS'] # not needed with ".ssh/authorized_keys2" file
  TODAY_FILE = ENV['TODAY_FILE'] || '.today'
  TODAY_PATH = File.join(ENV['HOME'], TODAY_FILE)

  def initialize
    @task_list = load_tasks()
    parse_command()
  end

  def parse_command
    cmd = $1 if ARGV[0] =~ /^-*(\w+)$/
    num = ARGV[1].to_i
    case cmd
    when 'help'
      return show_help() # don't show the task list
    when 'done'
      remove_task(num)
    when 'first'
      first_task(num)
    else
      add_task(ARGV.join(' ')) if ARGV.count > 0
    end
    show_task_list() or show_help()
  end

  def add_task(task)
    @task_list.push(task)
    save_tasks()
  end

  def remove_task(i = 1) # remove the first task by default
    i = 1 if i < 1
    @task_list.slice!(i-1) if i <= @task_list.count
    save_tasks()
  end

  def first_task(i = 1) # put the selected task first
    i = 1 if i < 1
    @task_list.unshift( @task_list.slice!(i-1) ) if i <= @task_list.count
    save_tasks()
  end

  def load_tasks
    sync_tasks(:get)
    return File.exist?(TODAY_PATH) ? YAML.load_file(TODAY_PATH) : []
  end

  def save_tasks
    File.open(TODAY_PATH, 'w') do |f|
      f.write @task_list.to_yaml
    end
    sync_tasks(:put)
  end

  def sync_tasks(action)
    return unless TODAY_HOST
    require 'net/scp'
    local = TODAY_PATH
    remote = TODAY_FILE
    case action
    when :put
      Net::SCP.upload!(TODAY_HOST, TODAY_USER, local, remote, password: TODAY_PASS)
    when :get
      Net::SCP.download!(TODAY_HOST, TODAY_USER, remote, local, password: TODAY_PASS)
    end
  end

  def show_task_list
    puts
    @task_list.each_with_index do |task, i|
      puts "[#{i+1}] #{task}" # e.g. "[1] get it finished"
    end
    puts
    return @task_list.count > 0 # i.e. did we show anything?
  end
end

Today.new

__END__
