#!/usr/bin/env ruby

# A simple "todo" list for today - by Kevin Hutchinson

require 'yaml'

class Today

  HIDDEN_YAML_FILE = File.join(ENV['HOME'], '.today')

  def initialize
    @task_list = load_tasks()
    parse_command()
  end

  def parse_command
    if ARGV[0] == 'help'
      show_help()
      return # without showing the task list
    elsif ARGV[0] == 'done'
      remove_task(ARGV[1].to_i)
    elsif ARGV.count > 0
      add_task(ARGV.join(' '))
    end
    show_task_list() or show_help()
  end

  def add_task(task)
    @task_list.push(task)
    save_tasks()
  end

  def remove_task(i = 1) # remove the first task by default
    i = 1 if i < 1
    @task_list.slice!(i-1) if i <= @task_list.count
    save_tasks()
  end

  def load_tasks
    return File.exist?(HIDDEN_YAML_FILE) ? YAML.load_file(HIDDEN_YAML_FILE) : []
  end

  def save_tasks
    File.open(HIDDEN_YAML_FILE, 'w') do |f|
      f.write @task_list.to_yaml
    end
  end

  def show_task_list
    @task_list.each_with_index do |task, i|
      puts "[#{i+1}] #{task}" # e.g. "[1] get it finished"
    end
    return @task_list.count > 0 # i.e. did we show anything?
  end

  def show_help
    puts <<End_of_help
This is a simple "todo" list for today's tasks.
Here's how to use the "today" command:

> today help              - show this help info
> today                   - list all tasks to finish today
> today get it finished   - add the task "get it finished"
> today done              - remove top item from the list
> today done 2            - remove item 2 from the list

End_of_help
  end
end

Today.new

__END__
